version: '3.7'

services:
  books:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - books-db
  books-db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=books
      - POSTGRES_PASSWORD=books
      - POSTGRES_DB=books_dev

volumes:
  postgres_data: